'from facebook_business.adobjects.adaccount import AdAccount' 
'from facebook_business.adobjects.campaign import Campaign' 
'from facebook_business.api import FacebookAdsApi' 
'access_token = "YOUR_ACCESS_TOKEN"' 
'ad_account_id = "act_YOUR_AD_ACCOUNT_ID"' 
'app_secret = "YOUR_APP_SECRET"' 
'app_id = "YOUR_APP_ID"' 
'FacebookAdsApi.init(app_id, app_secret, access_token)' 
'ad_account = AdAccount(ad_account_id)' 
'campaign = ad_account.create_campaign({' 
'  Campaign.Field.name: "New Campaign",' 
'  Campaign.Field.objective: Campaign.Objective.link_clicks,' 
'  Campaign.Field.status: Campaign.Status.paused,' 
'})' 
'print(campaign)' 
