'from facebook_business.api import FacebookAdsApi' 
'from facebook_business.adobjects.adaccount import AdAccount' 
'from facebook_business.adobjects.campaign import Campaign' 
'my_app_id = "<YOUR_APP_ID>"' 
'my_app_secret = "<YOUR_APP_SECRET>"' 
'my_access_token = "<YOUR_ACCESS_TOKEN>"' 
'FacebookAdsApi.init(my_app_id, my_app_secret, my_access_token)' 
'me = AdAccount("act_<AD_ACCOUNT_ID>")' 
'fields = []' 
'params = {"name": "My Campaign", "objective": "LINK_CLICKS", "status": "PAUSED", "buying_type": "AUCTION", "spend_cap": 10000}' 
'campaign = me.create_campaign(fields=fields, params=params)' 
'from facebook_business.adobjects.adaccount import AdAccount' 
'my_account = AdAccount("act_YOUR_AD_ACCOUNT_ID")' 
'my_account.create_campaign(params=params)' 
