'import requests, csv, bs4' 
'url = "https://www.ejemplo.com/productos"' 
'response = requests.get(url)' 
'soup = bs4.BeautifulSoup(response.text, "html.parser")' 
'productos = soup.find_all(class_="producto")' 
'with open("precios.csv", "w", newline='') as csvfile:' 
'    writer = csv.writer(csvfile)' 
'    writer.writerow(["Nombre", "Precio"])' 
'    for producto in productos:' 
'        nombre = producto.find(class_="nombre").get_text()' 
'        precio = producto.find(class_="precio").get_text()' 
'        writer.writerow([nombre, precio])' 
